databases:
  - name: ecommerce_db
    databaseName: ecommerce_db
    user: ecommerce_user
services:
  - type: web
    name: nexus-web
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: "gunicorn ecommerce.wsgi --log-file -"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: nexus-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: EMAIL_HOST_USER
        value: your-email@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: your-app-password
  - type: worker
    name: nexus-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A ecommerce worker -l info --pool=gevent"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: nexus-redis
          property: connectionString
      - key: SECRET_KEY
        sync: false  # Syncs with web service
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: EMAIL_HOST_USER
        value: your-email@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: your-app-password
  - type: redis
    name: nexus-redis
    ipAllowList: []  # Private networking
    maxmemoryPolicy: noeviction